# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-29 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-c_time'], 'verbose_name': 'yonghu', 'verbose_name_plural': 'yonghu'},
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('male', 'nan'), ('female', 'nv')], default='nan', max_length=32),
        ),
    ]
